### PR TITLE
[DTPORTAL-15343] [Php7 Upgrade:ifbyphone] [Static Analysis] Vendor: airbrake/phpbrake

### PR DESCRIPTION
**Pull request by kamerynn**
## [[DTPORTAL-15343] [Php7 Upgrade:ifbyphone] [Static Analysis] Vendor: airbrake/phpbrake](https://dialogtech.atlassian.net/browse/DTPORTAL-15320)
Run the static analysis tool on vendor `phpbrake`
Fix the following warnings:
```
Processing MonologHandler.php [PHP => 360 tokens in 45 lines]... DONE in 5ms (0 errors, 0 warnings)

FILE: /vagrant/Organic/vendor/airbrake/phpbrake/src/ErrorHandler.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 4 LINES
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 30 | WARNING | Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$code" was used, and possibly changed (by reference), on line
    |         | 27. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.NeedsInspection)
 34 | WARNING | Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$code" was used, and possibly changed (by reference), on line
    |         | 27. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.NeedsInspection)
 39 | WARNING | Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$code" was used, and possibly changed (by reference), on line
    |         | 27. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.NeedsInspection)
 43 | WARNING | Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$code" was used, and possibly changed (by reference), on line
    |         | 27. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.NeedsInspection)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 763ms; Memory: 8MB

~~~ PHP CodeSniffer Done 🎉
```

Post-fix result:
```
Processing MonologHandler.php [PHP => 360 tokens in 45 lines]... DONE in 4ms (0 errors, 0 warnings)
Time: 821ms; Memory: 8MB

~~~ PHP CodeSniffer Done 🎉

```

Reasoning:
- The `debug_backtrace` warnings refer to the `$code` variable, which is not modified, it is only used in a switch/case.

### Requires
- N/A

### Checklist
- [x] XSS
- [x] SQL injection
- [N/A] Add/Update Unit Tests

### Repositories
- [x] CRBN
- [x] Organic

[DTPORTAL-15343]: https://dialogtech.atlassian.net/browse/DTPORTAL-15343

### CODE REVIEW

**Comment by kamerynn** [comment]
@gfaza hey! made the changes here as well (identical to https://github.com/cloudvox/Ifbyphone/pull/2549/files). Can you review?

**Comment by kamerynn** [comment]
@jalubke is the release process for changes to this repo (a fork of a vendor) already known, or do you need more details? I can help gather info if you need

**Review by gfaza — APPROVED** [review]
👍

**Review by gfaza — CHANGES_REQUESTED** [review]
Hey!  looks great.  do you mind adding PHP 7.2 to travis, since you're already getting us PHP 7.2 ready?

**Comment by kamerynn** [comment]
@gfaza sure thing! will knock that out today.

Talking to @jalubke and I think we may need a dev/test branch for this, so that I can ship these changes to DEV only for testing. @gfaza @sfgeorge does that sound right, or do you see a simpler way?

**Comment by kamerynn** [comment]
These changes are really small, but it goes against our normal process to ship to all envs at once.

However, thinking about it now, will the changes be pulled into all envs when this gets merged, or will we need to update `composer.lock` for that to happen?

**Comment by gfaza** [comment]
@kamerynn - the only composer.lock that we keep in our repo (and that we'll need to update), is the CRBN one - the rest of our apps are meant to pull the "latest/greatest" from the vendor source during composer install/update.

**Comment by kamerynn** [comment]
Gotcha. So since this is also included in Organic's `composer.json`, may need to think of something here.

DEV/TEST branches probably aren't the way to go, now that I think of it. Since we don't have separate `composer.json` files per environment.

I'd think we would want to do an incremental branch or tag. We currently reference the branch name `support/v0.0.7.x` here: https://github.com/cloudvox/Ifbyphone/blob/develop/composer.json#L26. So we could start by creating a release/tag for `support/v0.0.7.1`, and update the IBP composer to reference that? I'm a bit of a newbie when it comes to Github and releases. (@jalubke)

@sfgeorge hey! do you have any opinion on this?

**Comment by kamerynn** [comment]
@gfaza also I added PHP 7.2 to the config. It didn't run for this PR but I see your test one, and it seems to run with a success. But the `HHVM` one fails

**Comment by kamerynn** [comment]
@jalubke @sfgeorge I think the best approach for this would be to start adding tags as "releases" for this repo.

We should make a tag for the current version, e.g. `support/v0.0.7.1`. I can open a PR to set that tag in Ifbyphone's `composer.json`. Then, we can merge this and create a `support/v0.0.7.2` tag, and I can open another PR to update composer again.

Any thoughts on that plan?

**Comment by kamerynn** [comment]
@mattcar hey, not sure who to chat with about this one. let me know if you have some time to talk through options here. I'm afraid that this will sit stagnant for a while

**Comment by sfgeorge** [comment]
@kamerynn @mattcar Yikes, I am sorry for not commenting earlier!  I do have some thoughts to share, but ultimately I refer to @mattcar on what is best.

Since I won't be typing out my thoughts on this for at least another couple of hours, I have no problem if you guys have to move forward with a correct course of action beforehand.  Sorry for having been a blocker!

**Comment by sfgeorge** [comment]
(Side note: the build failure on php hhvm could be forgiven/ignored.  When we later rebase our work atop the latest of the upstream airbrake/phpbrake, we'll get dd4849cb which drops support for hhvm completely)

**Comment by kamerynn** [comment]
@sfgeorge hey I talked with @mattcar and we are good to do the steps I mentioned. Did you have any thoughts on that before we moved forward? Totally open to ideas

**Comment by kamerynn** [comment]
@mattcar hey I don't think I can create a tag for this, unfortunately. Can you create a tag or release named `support/v0.0.7.1` that's based off the current `support/v0.0.7.x` branch?

**Comment by sfgeorge** [comment]
@kamerynn I like your plan and looks like @mattcar has created that tag 👍   I presume the next step is to merge this PR and then create the `support/v0.0.7.2` tag.

[My thoughts on use of support branches for an upstream open source project are kind of summed up here](https://github.com/cloudvox/Rediska/pull/6#pullrequestreview-208136529), and your strategy and mine are totally compatible. 👍

**Comment by kamerynn** [comment]
@sfgeorge Yep, the next step is to do `support/v0.0.7.2`. And I totally agree - we know at a glance that we based off of `v0.0.7` of the upstream project, which is great. and the additional version increment is basically the fork's patch version.

Thanks for the feedback!

**Comment by kamerynn** [comment]
@mattcar I just want to make the note that this should not block the PHP7 release. This is only for suppressing warnings, and I've already confirmed that the warnings are not an issue in PHP 7.

I've got Organic picking up the new tag, `v0.0.7.1`, but CRBN failed to deploy on the second deploy with the new tag (not sure why the first one worked). I will continue to debug.

A side note: `support/v0.0.7.1` is not a valid tag name to use in Composer. It does not follow the naming requirements: https://getcomposer.org/doc/04-schema.md#version

**Comment by kamerynn** [comment]
I recognize the problem, but I am not sure how to fix it:

CRBN's lockfile has two references to `phpbrake` - one for its own requirement of `phpbrake`, and one for Ifbyphone's requirement of `phpbrake`. In the current state, both requirements are pointed to the `support/v0.0.7.x` branch.

When I push the `composer.json` changes to `ibp-ghd/Ifbyphone/ghdcarbon`, and then run capistrano deploy while telling capistrano to pull in new changes for Ifbyphone, that results in Ifbyphone's requirement of `phpbrake` being updated.
(command: `bundle exec cap development deploy --set composer_update_packages=cloudvox/Ifbyphone`)

However, subsequent deploys will fail, as there is a mismatch of versions between CRBN and Ifbyphone's `phpbrake` requirement. One will update, but the other will not.

I've tried forcing CRBN's `phpbrake` requirement to update locally, by removing and readding the package:
```
./bin/composer.phar remove airbrake/phpbrake
./bin/composer.phar require airbrake/phpbrake:@dev
```

Depending on my state of local Ifbyphone, this results in two things, both of which are incorrect:
- If I have `Ifbyphone/ghdcarbon` checked out locally, then both `phpbrake` references in the lockfile will be updated to the correct version (good!) but Ifbyphone will now point to `ghdcarbon` (bad!)
- If I have `Ifbyphone/develop` checked out locally, then the Ifbyphone reference in the lockfile will not be affected (good!) but the `phpbrake` references will not be updated to the correct version (bad!)

I am at the point where I will need another brain looking at this problem with me... or a weekend to scratch my head on this problem. @sfgeorge, if it's alright, I'll schedule a meeting with you later today or early next week. Let me know if you have any ideas!

**Comment by sfgeorge** [comment]
Thanks @kamerynn, good sleuthing and I'm sorry this is causing so much trouble.

A few Qs here:

### Regarding Ifbyphone
* Can you share an Ifbyphone branch and/or PR that points to the desired ref of cloudvox/phpbrake?

### Regarding Organic
> I've got Organic picking up the new tag, v0.0.7.1, but CRBN failed to deploy on the second deploy with the new tag (not sure why the first one worked). I will continue to debug.
* I'm surprised this worked - actually my recommendation would be to leave it specified as `@dev` in Organic's composer.json, and only update the version requirement in Ifbyphone.

### Regarding both CRBN and Organic
* When you do a composer update, you'll need to request composer to update both cloudvox/Ifbyphone and cloudvox/phpbrake _at the same time_.  We need to move Ifbyphone to your new branch in order to see that a new version of phpbrake should be used;  but we also need to tell composer that it is okay for phpbrake to move.  That can be done like so:
  * locally: `./bin/composer.phar update cloudvox/Ifbyphone cloudvox/phpbrake`
  * via capistrano:
```
bundle exec cap development deploy --set composer_update_packages='cloudvox/Ifbyphone cloudvox/phpbrake'
```

**Comment by kamerynn** [comment]
@sfgeorge Awesome, thanks for the feedback.

Here's a diff for the IBP change: https://github.com/cloudvox/Ifbyphone/compare/develop...kamerynn:DTPORTAL-16121-phpbrake-lib-update-v0.0.7.1?expand=1

The Organic note - what you described is actually what I'm doing, sorry for the confusion. The Organic composer is still specified as `@dev`, but I hopped on the server and verified it pulled the new tag in the `phpbrake` dependency as specified by Ifbyphone.

I tried something similar to the capistrano command you gave, but I think I got the syntax wrong (it did not error, but it didn't work either). I will try that command later today or tonight, when I can potentially break DEV without anyone being affected.

Thanks for your help. I believe your command is going to fix the problem. I will let you know!

**Comment by kamerynn** [comment]
@sfgeorge I tried the command this morning and it didn't work, but I believe it's because I'm unable to get the change in `Ifbyphone/ghdcarbon` picked up by CRBN via `bundle exec cap development deploy --set composer_update_packages='cloudvox/Ifbyphone'`.

I'm going to rebuild my sandbox either today or tomorrow (I have meetings booked most of the day today). If it's alright with you, I'll go ahead and schedule some time tomorrow or Wednesday on your calendar. I'm hoping this is something we'll be able to knock out in a few minutes together because of some small glaring issue I'm having.

**Comment by kamerynn** [comment]
Hold on, I forgot that the Groundhog Day process doesn't set Ifbyphone back to `ghdcarbon`. That's why it is not updating. Trying again

**Comment by kamerynn** [comment]
No dice  🚫 🎲 

```
➜  crbn git:(secure-dev) bundle exec cap development deploy --set composer_update_packages='cloudvox/Ifbyphone cloudvox/phpbrake'

...

** [out :: ctrl-dev02.dialogtech.com] Your requirements could not be resolved to an installable set of packages.
 ** [out :: ctrl-dev02.dialogtech.com]
 ** [out :: ctrl-dev02.dialogtech.com] Problem 1
 ** [out :: ctrl-dev02.dialogtech.com] - Can only install one of: airbrake/phpbrake[v0.0.7.1, dev-support/v0.0.7.x].
 ** [out :: ctrl-dev02.dialogtech.com] - Can only install one of: airbrake/phpbrake[dev-support/v0.0.7.x, v0.0.7.1].
 ** [out :: ctrl-dev02.dialogtech.com] - Can only install one of: airbrake/phpbrake[dev-support/v0.0.7.x, v0.0.7.1].
 ** [out :: ctrl-dev02.dialogtech.com] - cloudvox/Ifbyphone dev-ghdcarbon requires airbrake/phpbrake v0.0.7.1 -> satisfiable by airbrake/phpbrake[v0.0.7.1].
 ** [out :: ctrl-dev02.dialogtech.com] - Installation request for cloudvox/ifbyphone dev-ghdcarbon -> satisfiable by cloudvox/Ifbyphone[dev-ghdcarbon].
 ** [out :: ctrl-dev02.dialogtech.com] - Installation request for airbrake/phpbrake (locked at dev-support/v0.0.7.x, required as @dev) -> satisfiable by airbrake/phpbrake[dev-support/v0.0.7.x].
 ** [out :: ctrl-dev02.dialogtech.com]
 ** [out :: ctrl-dev02.dialogtech.com] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
 ** [out :: cron-dev02.dialogtech.com] Package "cloudvox/phpbrake" listed for update is not installed. Ignoring.
 ** [out :: cron-dev02.dialogtech.com] Loading composer repositories with package information
```

yeah @sfgeorge, will find some time with you this or next week 😛

**Comment by sfgeorge** [comment]
@kamerynn Can you share your CRBN branch with me so I can try and repeat/troubleshoot?

**Comment by kamerynn** [comment]
@sfgeorge hey, sorry for the late response. There are no CRBN or Organic changes other than the CRBN lockfile (which I can't get to update correctly, so I have not committed anything).

The only code change is here: https://github.com/cloudvox/Ifbyphone/compare/develop...kamerynn:DTPORTAL-16121-phpbrake-lib-update-v0.0.7.1?expand=1

**Comment by kamerynn** [comment]
FYI: the first step in this change is to update the Ifbyphone library to reference a release tag that mirrors current state of the branch. Thanks to @sfgeorge and @mattcar, the deploy steps have been simplified. See this PR for more info: https://github.com/cloudvox/Ifbyphone/pull/2604

**Comment by kamerynn** [comment]
Closing this PR. My last day is Friday, and this is low importance in the grand scheme of things. If we ever need to release code to our fork of `phpbrake`, we'll need to follow through with this PR and the related Jira stories to avoid releasing code to all environments at the same time

**Comment by sfgeorge** [comment]
@kamerynn I'm very sorry we didn't get this over the finish line.  I need to make a backup of your branch here at least because all of your forks will be deleted after your last day :/ 

Thank you for your help on this.  At the very least, I'll make sure this gets in there.  Thanks very much man.

**Pull request closed without merging**
